approved = [
  "mit",
  "apache-2.0",
  "bsd-3-clause",
  "bsd-2-clause",
  "mpl-2.0",
]

ignored = [
  # Unsupported VCS
  "cloud.google.com/go",
  "cloud.google.com/go/storage",
  "google.golang.org/api",
  "google.golang.org/protobuf",
]

[header]
ignorePaths = ["vendor", ".gen", "plz-out"]
ignoreFiles = ["mock_*.go", "*_gen.go", "zz_generated.*.go", "generated.go"]
authors = ["Banzai Cloud", "Cisco Systems, Inc. and/or its affiliates", "Kube logging authors"]
template = """// Copyright Â© :YEAR: :AUTHOR:
//
// Licensed under the Apache License, Version 2.0 (the "License");
// you may not use this file except in compliance with the License.
// You may obtain a copy of the License at
//
//    http://www.apache.org/licenses/LICENSE-2.0
//
// Unless required by applicable law or agreed to in writing, software
// distributed under the License is distributed on an "AS IS" BASIS,
// WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
// See the License for the specific language governing permissions and
// limitations under the License."""
